# Generated by Django 4.2.6 on 2023-10-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('photo', models.ImageField(default=None, upload_to='images')),
                ('desc', models.TextField(max_length=255)),
            ],
        ),
    ]
