# Generated by Django 4.2.6 on 2023-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
    ]
