# Generated by Django 4.2.6 on 2023-10-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action',
            field=models.CharField(choices=[('pending', 'Pending'), ('received_by_owner', 'Received by Owner'), ('confirm', 'Confirm'), ('reject', 'Reject'), ('on_the_way', 'On the Way')], default='pending', max_length=20),
        ),
    ]
