# Generated by Django 4.2.6 on 2023-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_order_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('ordered', 'Ordered'), ('shipped', 'Shipped')], default='in_cart', max_length=20),
        ),
    ]
